<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from osdi/xml/schema/CRM/Osdi/OsdiRemoteSystem.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:82a41dd3c121ea1b9780a103b5a2d013)
 */
use \CRM_Osdi_ExtensionUtil as E;

/**
 * Database access object for the OsdiRemoteSystem entity.
 */
class CRM_OSDI_DAO_RemoteSystem extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_osdi_remote_system';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique OsdiRemoteSystem ID
   *
   * @var int
   */
  public $id;

  /**
   * Display name
   *
   * @var string
   */
  public $label;

  /**
   * API entry point (AEP) URL
   *
   * @var string
   */
  public $entry_point;

  /**
   * API token
   *
   * @var string
   */
  public $api_token;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_osdi_remote_system';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Osdi Remote Systems') : E::ts('Osdi Remote System');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique OsdiRemoteSystem ID'),
          'required' => TRUE,
          'where' => 'civicrm_osdi_remote_system.id',
          'table_name' => 'civicrm_osdi_remote_system',
          'entity' => 'OsdiRemoteSystem',
          'bao' => 'CRM_OSDI_DAO_RemoteSystem',
          'localizable' => 0,
          'add' => NULL,
        ],
        'label' => [
          'name' => 'label',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name'),
          'description' => E::ts('Display name'),
          'maxlength' => 255,
          'size' => 64,
          'import' => TRUE,
          'where' => 'civicrm_osdi_remote_system.label',
          'export' => TRUE,
          'table_name' => 'civicrm_osdi_remote_system',
          'entity' => 'OsdiRemoteSystem',
          'bao' => 'CRM_OSDI_DAO_RemoteSystem',
          'localizable' => 1,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'entry_point' => [
          'name' => 'entry_point',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('API Entry Point URL'),
          'description' => E::ts('API entry point (AEP) URL'),
          'maxlength' => 1023,
          'size' => 64,
          'import' => TRUE,
          'where' => 'civicrm_osdi_remote_system.entry_point',
          'export' => TRUE,
          'table_name' => 'civicrm_osdi_remote_system',
          'entity' => 'OsdiRemoteSystem',
          'bao' => 'CRM_OSDI_DAO_RemoteSystem',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'api_token' => [
          'name' => 'api_token',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('API Token'),
          'description' => E::ts('API token'),
          'maxlength' => 1023,
          'size' => 64,
          'import' => TRUE,
          'where' => 'civicrm_osdi_remote_system.api_token',
          'export' => TRUE,
          'table_name' => 'civicrm_osdi_remote_system',
          'entity' => 'OsdiRemoteSystem',
          'bao' => 'CRM_OSDI_DAO_RemoteSystem',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return CRM_Core_DAO::getLocaleTableName(self::$_tableName);
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'osdi_remote_system', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'osdi_remote_system', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
