<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from osdi-client/xml/schema/CRM/OSDI/OsdiSyncProfile.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:0ac06b0d4f1916b9fa75001f2a6ba775)
 */
use CRM_OSDI_ExtensionUtil as E;

/**
 * Database access object for the SyncProfile entity.
 */
class CRM_OSDI_DAO_SyncProfile extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_osdi_sync_profile';

  /**
   * Field to show when displaying a record.
   *
   * @var string
   */
  public static $_labelField = 'label';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique OsdiSyncProfile ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Is this default OSDI SyncProfile?
   *
   * @var bool|string|null
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_default;

  /**
   * User-friendly label for the sync configuration
   *
   * @var string|null
   *   (SQL type: varchar(128))
   *   Note that values will be retrieved from the database as a string.
   */
  public $label;

  /**
   * API entry point (AEP) URL
   *
   * @var string|null
   *   (SQL type: varchar(1023))
   *   Note that values will be retrieved from the database as a string.
   */
  public $entry_point;

  /**
   * API token
   *
   * @var string|null
   *   (SQL type: varchar(1023))
   *   Note that values will be retrieved from the database as a string.
   */
  public $api_token;

  /**
   * Three-level associative array (category => key => class name) of classes to register with the OSDI Client's container/service locator
   *
   * @var string|null
   *   (SQL type: longtext)
   *   Note that values will be retrieved from the database as a string.
   */
  public $classes;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_osdi_sync_profile';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Sync Profiles') : E::ts('Sync Profile');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique OsdiSyncProfile ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_osdi_sync_profile.id',
          'table_name' => 'civicrm_osdi_sync_profile',
          'entity' => 'SyncProfile',
          'bao' => 'CRM_OSDI_DAO_SyncProfile',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'is_default' => [
          'name' => 'is_default',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Default SyncProfile'),
          'description' => E::ts('Is this default OSDI SyncProfile?'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_osdi_sync_profile.is_default',
          'default' => '0',
          'table_name' => 'civicrm_osdi_sync_profile',
          'entity' => 'SyncProfile',
          'bao' => 'CRM_OSDI_DAO_SyncProfile',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'label' => [
          'name' => 'label',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Label'),
          'description' => E::ts('User-friendly label for the sync configuration'),
          'maxlength' => 128,
          'size' => 128,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_osdi_sync_profile.label',
          'export' => TRUE,
          'table_name' => 'civicrm_osdi_sync_profile',
          'entity' => 'SyncProfile',
          'bao' => 'CRM_OSDI_DAO_SyncProfile',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'entry_point' => [
          'name' => 'entry_point',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('API Entry Point URL'),
          'description' => E::ts('API entry point (AEP) URL'),
          'maxlength' => 1023,
          'size' => 64,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_osdi_sync_profile.entry_point',
          'export' => TRUE,
          'table_name' => 'civicrm_osdi_sync_profile',
          'entity' => 'SyncProfile',
          'bao' => 'CRM_OSDI_DAO_SyncProfile',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'api_token' => [
          'name' => 'api_token',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('API Token'),
          'description' => E::ts('API token'),
          'maxlength' => 1023,
          'size' => 64,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_osdi_sync_profile.api_token',
          'export' => TRUE,
          'table_name' => 'civicrm_osdi_sync_profile',
          'entity' => 'SyncProfile',
          'bao' => 'CRM_OSDI_DAO_SyncProfile',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'classes' => [
          'name' => 'classes',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Classes to Use'),
          'description' => E::ts('Three-level associative array (category => key => class name) of classes to register with the OSDI Client\'s container/service locator'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_osdi_sync_profile.classes',
          'export' => TRUE,
          'table_name' => 'civicrm_osdi_sync_profile',
          'entity' => 'SyncProfile',
          'bao' => 'CRM_OSDI_DAO_SyncProfile',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'osdi_sync_profile', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'osdi_sync_profile', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
