-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_osdi_sync_profile`;
DROP TABLE IF EXISTS `civicrm_osdi_match`;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_osdi_match
-- *
-- * Linkages between CiviCRM contacts and their counterparts on remote OSDI systems
-- *
-- *******************************************************/
CREATE TABLE `civicrm_osdi_match` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique OsdiMatch ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `sync_profile_id` int unsigned COMMENT 'FK to OSDI Sync Profile',
  `remote_person_id` varchar(255) DEFAULT NULL COMMENT 'FK to identifier field on remote system',
  `sync_origin_modified_time` datetime DEFAULT NULL COMMENT 'Modification date and time of the origin record as of the last sync, in UTC',
  `sync_target_modified_time` datetime DEFAULT NULL COMMENT 'Modification date and time of the target record as of the last sync, in UTC',
  `sync_origin` tinyint DEFAULT NULL COMMENT '0 if local CiviCRM was the origin of the last sync, 1 if remote system was the origin',
  `sync_status` varchar(255) DEFAULT NULL COMMENT 'Status of the last sync',
  PRIMARY KEY (`id`),
  INDEX `index_contact_id`(contact_id),
  INDEX `index_sync_profile_id`(sync_profile_id),
  INDEX `index_remote_person_id`(remote_person_id),
  INDEX `index_sync_origin_modified_time`(sync_origin_modified_time),
  INDEX `index_sync_target_modified_time`(sync_target_modified_time),
  INDEX `index_sync_status`(sync_status),
  CONSTRAINT FK_civicrm_osdi_match_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_osdi_match_sync_profile_id FOREIGN KEY (`sync_profile_id`) REFERENCES `civicrm_osdi_sync_profile`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_osdi_sync_profile
-- *
-- * OSDI Sync configurations
-- *
-- *******************************************************/
CREATE TABLE `civicrm_osdi_sync_profile` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique OsdiSyncProfile ID',
  `is_default` tinyint DEFAULT 0 COMMENT 'Is this default OSDI SyncProfile?',
  `label` varchar(128) COMMENT 'User-friendly label for the sync configuration',
  `entry_point` varchar(1023) COMMENT 'API entry point (AEP) URL',
  `api_token` varchar(1023) COMMENT 'API token',
  `remote_system` varchar(127) COMMENT 'class name of Remote System',
  `matcher` varchar(127) COMMENT 'class name of Matcher',
  `mapper` varchar(127) COMMENT 'class name of Mapper',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS=1;
