-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_osdi_remote_system`;
DROP TABLE IF EXISTS `civicrm_osdi_match`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_osdi_remote_system
-- *
-- * Remote OSDI-accessible databases
-- *
-- *******************************************************/
CREATE TABLE `civicrm_osdi_remote_system` (
    `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique OsdiRemoteSystem ID',
    `label` varchar(255) COMMENT 'Display name',
    `entry_point` varchar(1023) COMMENT 'API entry point (AEP) URL',
    `api_token` varchar(1023) COMMENT 'API token',
    PRIMARY KEY (`id`)
);

-- /*******************************************************
-- *
-- * civicrm_osdi_match
-- *
-- * Linkages between CiviCRM contacts and their counterparts on remote OSDI systems
-- *
-- *******************************************************/
CREATE TABLE `civicrm_osdi_match` (
    `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique OsdiMatch ID',
    `contact_id` int unsigned COMMENT 'FK to Contact',
    `remote_system_id` int unsigned COMMENT 'FK to OSDI Remote System',
    `remote_person_id` varchar(255) DEFAULT NULL COMMENT 'FK to identifier field on remote system',
    `sync_origin_modified_time` datetime DEFAULT NULL COMMENT 'Modification date and time of the origin record as of the last sync, in UTC',
    `sync_target_modified_time` datetime DEFAULT NULL COMMENT 'Modification date and time of the target record as of the last sync, in UTC',
    `sync_origin` tinyint DEFAULT NULL COMMENT '0 if local CiviCRM was the origin of the last sync, 1 if remote system was the origin',
    PRIMARY KEY (`id`),
    INDEX `index_contact_id` (contact_id),
    INDEX `index_remote_system_id` (remote_system_id),
    INDEX `index_remote_person_id` (remote_person_id),
    INDEX `index_sync_origin_modified_time` (sync_origin_modified_time),
    INDEX `index_sync_target_modified_time` (sync_target_modified_time),
    CONSTRAINT FK_civicrm_osdi_match_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE CASCADE,
    CONSTRAINT FK_civicrm_osdi_match_remote_system_id FOREIGN KEY (`remote_system_id`) REFERENCES `civicrm_osdi_remote_system` (`id`) ON DELETE CASCADE
);



 